language: objective-c  #1
osx_image: xcode9.2 #2
xcode_project: ladeBilen.xcworkspace #3
xcode_scheme: ladeBilen #4
xcode_sdk: iphonesimulator11.2 #5

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.2 -workspace ladeBilen.xcworkspace -scheme ladeBilen CODE_SIGNING_REQUIRED=NO

